### ISSUE TITLE
Error with 2 modules in the same story file

### ISSUE THREAD

**Issue by carlotm** [phenixdigital/phoenix_storybook#261] opened 2023-03-10 14:18 UTC
Hi all,

my story file looks like this:

```
defmodule Storybook.Examples.LiveForm do
  use PhoenixStorybook.Story, :example
  alias Storybook.Examples.LiveForm.Skema

  @impl true
  def mount(_, _, socket) do
    changeset = Skema.changeset(%Skema{})
    {:ok, socket}
  end

  def render(assigns), do: ~H"o/"
end

defmodule Storybook.Examples.LiveForm.Skema do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field(:image, :string)
  end

  def changeset(item, attrs \\ %{}) do
    item
    |> cast(attrs, [:image])
    |> validate_required([:image])
  end
end
```

I got this error when trying to visit the story page:

```
** (CompileError) storybook/examples/live_form.story.exs:7: Storybook.Examples.LiveForm.Skema.__struct__/1 is undefined, cannot expand struct Storybook.Examples.LiveForm.Skema. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
    expanding struct: Storybook.Examples.LiveForm.Skema.__struct__/1
    storybook/examples/live_form.story.exs:7: Storybook.Examples.LiveForm.mount/3
```

Am I doing something wrong here?

Thank you

**Comment by cblavier** [comment] 2023-03-10 14:24
Is this the same issue than #260? I'll get it fixed next week

**Comment by carlotm** [comment] 2023-03-10 14:29
It could be, yes.
If that's ok I would like to keep this open, but you can comment on the other, and I'll test the fix.

Thanks for the effort.

**Comment by cblavier** [comment] 2023-03-15 15:42
Hey @carlotm  
Any chance you can test the main branch to see if the issue is fixed for you?

**Comment by carlotm** [comment] 2023-03-15 15:51
Hi @cblavier 

I am updated at commit 14b9e76159e4914753a64b56b41812745e7b4063 and it didn't solve the issue (same error).

As I see having an additional module inside the story a very specific edge case, and there is a method to achieve the same (using the `extra_resources` function), I am ok with closing this issue.

Kind Regards,
Carlo

**Comment by cblavier** [comment] 2023-03-15 15:58
I'm fine with closing the issue :) Thanks, Carlo!

**Closed by cblavier** 2023-03-15 15:58 UTC
